version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/ohyahgit/deepsource-test"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "black"
